#!/bin/sh
xrandr --output DP-1-1-1 --off 
xrandr --output DP-1-1 --off
xrandr --output HDMI-2 --off
xrandr --output HDMI-1 --off
xrandr --output DP-2 --off
xrandr --output DP-1 --off
xrandr --output DP-1-8 --mode 2560x1440 --pos 0x0 --rotate normal
xrandr --output DP-1-1-8 --mode 2560x1440 --pos 2560x0 --rotate normal
xrandr --output eDP-1 --primary --mode 2560x1440 --pos 0x1440 --rotate normal
